version: '2'
services:
    featureflowexampleangularonejava-app:
        image: featureflowexampleangularonejava
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://featureflowexampleangularonejava-mysql:3306/featureflowexampleangularonejava?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    featureflowexampleangularonejava-mysql:
        extends:
            file: mysql.yml
            service: featureflowexampleangularonejava-mysql
